// users actions
export const FETCH_USER='FETCH_USER'
export const FETCH_USER_AUTHDETAILS='FETCH_USER_AUTHDETAILS'
export const FETCH_USER_POSTS='FETCH_USER_POSTS'
export const FETCH_USER_FOLLOW='FETCH_USER_FOLLOW'



// subconn actions
export  const FETCH_SUBCONN='FETCH_SUBCONN'
export const FETCH_SUBCONN_POSTS='FETCH_SUBCONN_POSTS'
export const FETCH_SUBCONN_FOLLOWERS='FETCH_SUBCONN_FOLLOWERS'
export const FETCH_SUBCONN_FOLLOWEES='FETCH_SUBCONN_FOLLOWEES'