# Generated by Django 3.1 on 2021-02-28 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210228_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subconn_id',
        ),
    ]
