# Generated by Django 3.1.7 on 2021-04-15 11:17

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_subconn_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.FileField(blank=True, upload_to=posts.models.User_Directory, verbose_name='path'),
        ),
    ]
