# Generated by Django 3.1 on 2021-02-26 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subconn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subconn_name', models.CharField(max_length=100, unique=True)),
                ('num_subconn_followers', models.PositiveBigIntegerField(default=0)),
                ('subconn_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subconn_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubconnFollower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followee_s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee_s', to='subconns.subconn')),
                ('follower_s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_s', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='subconnfollower',
            constraint=models.UniqueConstraint(fields=('follower_s', 'followee_s'), name='subconn_follow_unique'),
        ),
    ]
