# Generated by Django 3.1 on 2021-02-28 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_subconn_id'),
        ('subconns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubconnPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('subconn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subconns.subconn')),
            ],
        ),
    ]
