# Generated by Django 3.1.7 on 2021-04-07 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subconns', '0002_subconnpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subconnpost',
            name='post',
        ),
        migrations.AddField(
            model_name='subconnpost',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subconnpost',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subconnpost',
            name='num_comments',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subconnpost',
            name='num_likes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subconnpost',
            name='post_text',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='subconnpost',
            name='post_title',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='subconnpost',
            name='post_type',
            field=models.FileField(blank=True, upload_to='subconn_posts/', verbose_name='path'),
        ),
        migrations.AddField(
            model_name='subconnpost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subconnpost',
            name='subconn',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='subconns.subconn'),
        ),
        migrations.CreateModel(
            name='SubconnLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subconns.subconnpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubconnComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=400)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subconns.subconnpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='subconnlike',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='subconn_post_like_unique'),
        ),
    ]
