# Generated by Django 3.1.7 on 2021-04-07 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subconns', '0003_auto_20210407_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subconnpost',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subconnpost',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subconnpost',
            name='post_title',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='subconnpost',
            name='subconn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subconns.subconn'),
        ),
        migrations.AlterField(
            model_name='subconnpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.user'),
        ),
    ]
