# Generated by Django 3.1.7 on 2021-04-15 11:17

from django.db import migrations, models
import subconns.models


class Migration(migrations.Migration):

    dependencies = [
        ('subconns', '0004_auto_20210407_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='subconn',
            name='cover_pic',
            field=models.ImageField(default='default.jpg', upload_to=subconns.models.User_Directory_C),
        ),
        migrations.AddField(
            model_name='subconn',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to=subconns.models.User_Directory),
        ),
    ]
